apps/auth.py
from flask.ext.login import LoginManager, login_user, logout_user, current_user, login_required
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField, validators, HiddenField, ValidationError
from wtforms import TextAreaField, BooleanField
from wtforms.validators import Required, EqualTo, Optional
from wtforms.validators import Length, Email
import logging
from model import *
import views
from flask import current_app, session, render_template, url_for, request, redirect, flash, abort, g, Blueprint
from sqlalchemy.orm import scoped_session, relation, sessionmaker
from sqlalchemy import select
import pprint 

pp = pprint.PrettyPrinter(indent=2)

auth = Blueprint('auth', __name__)

class SignupForm(Form):
    email = TextField('Email address', validators=[
            Required('Please provide a valid email address'),
            Length(min=6, message=(u'Email address too short')),
            Email(message=(u'That\'s not a valid email address.'))])
    password = PasswordField('Pick a secure password', validators=[
            Required(),
            EqualTo('confirm', message=(u'Passwords must match')),
            Length(min=6, message=(u'Please give a longer password.'))])
    confirm = PasswordField('Repeat Password')
    username = TextField('Choose your username', validators=[Required()])
    agree = BooleanField('I agree all your Terms of Services',
            validators=[Required(u'You must accept our Terms of Service')])

    def __repr__(self):
        return "<{0}:{1.username}:{1.email}>".format(SignupForm, self)

#logging
logger = logging.getLogger(__name__)

# login manager
login_manager = LoginManager()
login_manager.login_view = 'login'

@auth.before_request
def before_request():
	g.user = current_user

@login_manager.user_loader
def load_user(userid):
	return views.orm_session.query(User).get(userid)

@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == 'GET':
        return render_template('login.html')

    username = request.form['username']
    password = request.form['password']
    remember_me = False
    if 'remember_me' in request.form:
        remember_me = True
    registered_user = views.orm_session.query(User).filter_by(username=username,password=password).first()
    logger.info("Registered user = %s", registered_user)
    if registered_user is None:
        flash('Username or Password is invalid' , 'error')
        return redirect(url_for('login'))
    login_user(registered_user, remember = remember_me)
    flash('Logged in successfully')
    return redirect(request.args.get('next') or url_for('views.home'))

@auth.route("/logout")
@login_required
def logout():
    user = current_user
    user.authenticated = False
    views.orm_session.add(user)
    views.orm_session.commit()
    logout_user()
    return redirect(url_for("login"))
    
@auth.route("/signup", methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        user = User()
        form = SignupForm(request.form, obj=user)
        if form.validate():
            form.populate_obj(user)
            user_exist = User.query.filter_by(username=form.username.data).first()
            email_exist = User.query.filter_by(email=form.email.data).first()
            if user_exist:
                form.username.errors.append('Username already taken')
            if email_exist:
                form.email.errors.append('Email already use')
            if user_exist or email_exist:
                return render_template('signup.html', form = form, page_title = 'Signup to Courses System')
            else:
                user.authenticated = True
                views.orm_session.add(user)
                views.orm_session.commit()
                #current_user = user
                flash('Thanks for signing up.')
                return redirect(url_for('views.courses'))
        else:
            #pp.pprint(form)
            return render_template('signup.html', form = form, page_title = 'Signup to Courses System')
    return render_template('signup.html', form = SignupForm(), page_title = 'Signup to Courses System')

apps/views.py
# -*- coding: utf-8 -*-

import message
import codecs
from model import *
from flask import Flask, request, redirect, render_template, session, g, url_for, Blueprint
import jinja2
from sqlalchemy.orm import scoped_session, relation, sessionmaker
from sqlalchemy import select, create_engine
import datetime
import sys
from flask.ext.login import login_required, current_user
import logging
from os.path import join, dirname


views = Blueprint('views', __name__)

#logging
logger = logging.getLogger(__name__)

# utf-8 unicode required
reload(sys)
sys.setdefaultencoding("utf-8")

# ORM Session
_cwd = dirname(__file__)
engine = create_engine('sqlite:///' + join(_cwd, 'database/courses.sqlite'))
Session = scoped_session(sessionmaker(autocommit=False,
                                         autoflush=False,
                                         bind=engine))
orm_session = Session()
orm_session._model_changes = {} # flask.ext.sqlalchemy added attribute

@views.route('/test')
@login_required
def test():
    session = request.environ['beaker.session']
    session['test'] = session.get('test', 0) + 1
    session.save()
    return 'Test counter: %d' % session['test']

@views.before_request
def before_request():
    g.user = current_user

@views.route('/')
def home():
	return render_template('home.html')

@views.route('/courses')
def courses():
	courses = orm_session.query(Course).order_by('-id')
	return render_template('courses.html', courses=courses)

# New
@views.route('/new-course', methods=['POST'])
def new_course():
	name = request.form["name"].decode("utf-8")

	if len(name) > 0:
		record = Course(name=name, active=True)

		orm_session.add(record)
		orm_session.commit()

		message.success("sucessful!")
	else:
		message.error("Failed!")

	return redirect(url_for('courses'))

@views.route('/update-course/<int:id>', methods=['POST'])
def update_course(id):
	course = orm_session.query(Course).filter(Course.id == id).first()

	name = request.form["name"].decode("utf-8")

	if course:
		course.name = name
		orm_session.add(course)
		orm_session.commit()
	else:
		message.error("Failed")

	return redirect(url_for("home"))

# Delete
@views.route('/delete-course/<int:id>')
def delete(id):
	find_students = select([CourseStudentLink.course_id, CourseStudentLink.student_id]).select_from(CourseStudentLink.__table__).where(CourseStudentLink.course_id == id)

	rs = orm_session.execute(find_students)
	student = rs.fetchone()

	if student:
		message.error(u"还有学生选了这门课")
	else:
		course = orm_session.query(Course).filter(Course.id==id).first()
		logger.info("course name: %s", course)

		if course:
			orm_session.delete(course)
			orm_session.commit()

	return redirect(url_for('courses'))

@views.route('/edit-course/<int:id>')
def edit_course(id):
	course = orm_session.query(Course).filter(Course.id == id).first()
	logger.info("editing course: %s", course)

	if course:
		message.success("successful!")
		return render_template('edit-course.html', course=course)
	else:
		message.error("Failed!")
		return redirect(url_for("courses"))

@views.route('/subjects')
def list_subjects():
	subjects = orm_session.query(Subject).order_by('-id')

	return render_template('subjects.html', subjects=subjects)

@views.route('/edit-subject/<int:id>')
def edit_subject(id):
	subject = orm_session.query(Subject).filter(Subject.id == id).first()

	if subject:
		message.success("successful!")
		return render_template('edit-subject.html', subject=subject)
	else:
		message.error("Failed!")
		return redirect("/")

@views.route('/delete-subject/<int:id>')
def delete_subject(id):
	subject = orm_session.query(Subject).filter(Subject.id == id).first()
	if subject:
		message.success("successful!")
		orm_session.delete(subject)
		orm_session.commit()
	else:
		message.error("Failed!")
	
	return redirect('/subjects')

@views.route('/new-subject', methods=['POST'])
def new_subject():
	subject_name = request.form["name"].decode("utf-8")
	duration = request.form["duration"].decode("utf-8")
	tier = request.form["tier"].decode("utf-8")

	if len(subject_name) >0 and len(duration) > 0 and tier:
		subject = Subject(name=subject_name, duration=duration, tier=tier)
		orm_session.add(subject)
		orm_session.commit()
		message.success("successful!")
	else:
		message.error("Failed!")
	
	return redirect('/subjects')

@views.route('/update-subject/<int:id>', methods=['POST'])
def update_subject(id):
	subject = orm_session.query(Subject).filter(Subject.id==id).first()
	logger.info("Subject object = %s", subject)
	name = request.form["name"].decode("utf-8")
	duration = request.form["duration"].decode("utf-8")
	if subject:
		logger.info("Subject name = %s and duration = %s.\n", \
		 "textfield name = %s, textfield duration = %s\n",
			subject.name, subject.duration, name ,duration)
		if subject.name != name:
			subject.name = name
		if subject.duration != duration:
			subject.duration = duration
		orm_session.add(subject)
		orm_session.commit()
		message.success("successful")
	else:
		message.error("Failed!")

	return redirect('/subjects')
	
### Operations for students

@views.route('/students')
def list_students():
	students = orm_session.query(Student).order_by('-id')
	return render_template('students.html', students=students)

@views.route('/new-student', methods=['POST'])
def new_student():
	firstname = request.form["firstname"].decode("utf-8")
	lastname = request.form["lastname"].decode("utf-8")
	
	if request.form["paid"] == 'on':
		paid = True
	else:
		paid = False

	if len(firstname) > 0 and len(lastname) > 0:
		record = Student(firstname=firstname, lastname=lastname, paid=paid, active=True)

		orm_session.add(record)
		orm_session.commit()

		message.success("sucessful!")
	else:
		message.error("Failed!")

	return edirect("/students")

@views.route('/edit-student/<int:id>')
def edit_student(id):
	student = orm_session.query(Student).filter(Student.id==id).first()

	if student:
		logger.info("student = %s", student)
		message.success("successful!")
		return render_template('edit-student.html', student=student)
	else:
		message.error("Failed!")
		return redirect("/students")

@views.route('/delete-student/<int:id>')
def delete_student(id):
	student = orm_session.query(Student).filter(Student.id==id).first()

	if student:
		logger.info("student = %s", student)
		orm_session.delete(student)
		orm_session.commit()
		orm_session.close()
		message.success("sucessful!")
	else:
		message.error(u"找不到记录")

	return redirect('/students')

@views.route('/update-student/<int:id>', methods=['POST'])
def update_student(id):
	student = orm_session.query(Student).filter(Student.id==id).first()

	name = request.form["name"].decode("utf-8")

	if student:
		student.name = name
		orm_session.add(student)
		orm_session.commit()
		message.success("successful")
	else:
		message.error("Failed")

	return redirect("students")

def validate_birthdate(birthdate):
	if len(birthdate) > 0:
		birthdate = datetime.datetime.strptime(birthdate, "%Y-%m-%d")
	else:
		message.error("Birth date should not be empty.")

def validate_form_field_not_empty(firstname, lastname, birthdate):
	return len(firstname) > 0 and len(lastname) > 0 and birthdate is not None


### Teacher opeartions
@views.route('/teachers')
def list_teachers():
	teachers = orm_session.query(Teacher).order_by('-id')
	return render_template('teachers.html', teachers=teachers)

@views.route('/new-teacher', methods=['POST'])
def new_teacher():
	firstname = request.form["firstname"].decode("utf-8")
	lastname = request.form["lastname"].decode("utf-8")
	birthdate = request.form["birthdate"].decode("utf-8")

	validate_birthdate(birthdate)

	nationality = request.form["nationality"].decode("utf-8")
	visa_status = request.form["visa_status"].decode("utf-8")
	salary_per_hour = request.form["salary_per_hour"].decode("utf-8")
	if validate_form_field_not_empty(firstname, lastname, birthdate):
		record = Teacher(firstname=firstname, lastname=lastname, \
			birthdate=birthdate, nationality=nationality, visa_status=visa_status, \
			salary_per_hour = salary_per_hour, active=True)

		orm_session.add(record)
		orm_session.commit()

		message.success("sucessful")
	else:
		message.error("Failed!")

	return redirect(url_for("teachers"))

@views.route('/delete-teacher/<int:id>')
def delete_teacher(id):
	teacher = orm_session.query(Teacher).filter(Teacher.id==id).first()

	if teacher:
		logger.info("deleting teacher %s", teacher)
		orm_session.delete(teacher)
		orm_session.commit()
		orm_session.close()
		message.success("successful!")
	else:
		message.error(u"找不到记录")

	return redirect(url_for("teachers"))

@views.route('/edit-teacher/<int:id>')
def edit_teacher(id):
	teacher = orm_session.query(Teacher).filter(Teacher.id==id).first()

	if teacher:
		logger.info("Editing teacher %s", teacher)
		message.success("successful")
		return render_template('edit-teacher.html', teacher=teacher)
	else:
		message.error("Failed!")
		return redirect(url_for("teachers"))

@views.route('/update-teacher/<int:id>', methods=['POST'])
def update_teacher(id):
	teacher = orm_session.query(Teacher).filter(Teacher.id==id).first()

	firstname = request.form["firstname"].decode("utf-8")
	lastname = request.form["lastname"].decode("utf-8")
	birthdate = request.form["birthdate"].decode("utf-8")

	validate_birthdate(birthdate)

	nationality = request.form["nationality"].decode("utf-8")
	visa_status = request.form["visa_status"].decode("utf-8")
	salary_per_hour = request.form["salary_per_hour"].decode("utf-8")

	if validate_form_field_not_empty(firstname, lastname, birthdate):
		logger.info("Teacher's name is %s", firstname + ' ' + lastname)
		teacher.firstname = firstname
		teacher.lastname = lastname
		teacher.birthdate = birthdate
		teacher.nationality = nationality
		teacher.visa_status = visa_status
		teacher.salary_per_hour = salary_per_hour
		orm_session.add(teacher)
		orm_session.commit()
		message.success("successful")
	else:
		message.error("Failed")

	return redirect("teachers")

apps/templates/aboutus.html
{% extends "base.html" %}

apps/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}My Project{% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- SmartMenus jQuery Bootstrap Addon CSS -->
    <link href="{{ url_for('static', filename='css/jquery.smartmenus.bootstrap.css')}}" rel="stylesheet">
    {% block css %}{% endblock %}
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{{ url_for('static', filename='css/bootstrap-responsive.min.css') }}" rel="stylesheet">

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link rel="apple-touch-icon" href="{{ url_for('static', filename='images/apple-touch-icon.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='images/apple-touch-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='images/apple-touch-icon-114x114.png') }}">
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="navbar-header">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="navbar-brand" href="#">Course System</a>
      </div>
          <div class="nav-collapse">
            {% set navigation_bar = [
              ('views.home', 'index', 'Home'),
              ('views.courses', 'courses', 'Courses'),
              ('views.list_subjects', 'subjects', 'Subjects'),
              ('views.list_students', 'students', 'Students'),
              ('views.list_teachers', 'teachers', 'Teachers'),
              ('views.about', 'aboutus', 'About'),
              ('views.contact', 'contact', 'Contact'),
            ] -%}
            {% set active_page = active_page|default('index') -%}
            <ul class="nav navbar-nav">
              {% for href, id, caption in navigation_bar %}
                <li {% if id == active_page %} class="active"{% endif %}>
                <a href="{{ url_for(href)|e }}">{{ caption|e }}</a></li>
              {% endfor %}
            </ul>
          </div><!--/.nav-collapse -->
        {% if g.user.is_authenticated()%}
              <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        {% endif %}
      
    </div>

    <div class="container">
        <div class="content">
            {% if current_user.is_authenticated() %}
              Hi {{ current_user.name }}, welcome to Courses System!
            {% endif %}
            {% block content %}
                <h1>Oops, nothing here</h1>
                <p>This page is empty.</p>
            {% endblock %}
        </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ url_for('static', filename='js/jquery-1.11.1.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <!-- SmartMenus jQuery plugin -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.smartmenus.js')}}"></script>

    <!-- SmartMenus jQuery Bootstrap Addon -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.smartmenus.bootstrap.js')}}"></script>
    {% block javascript %}{% endblock %}

  </body>
</html>

apps/templates/contact_us.html
{% extends "base.html" %}

apps/templates/courses.html
{% extends "base.html" %}
{% set active_page = "courses" %}
{% block title %}
	Courses system
{% endblock %}

{% block content %}
    
    <h2>新增课程</h2>
	<form action="/new-course" method="post" id="post_new">
		<p><input class="large" type="text" name="name" placeholder="名称" /></p>
		<p><input type="submit" class="submit" value="添加" /></p>
	</form>

	</br>

	<h2>已有课程</h2>
	<table class="table table-striped table-bordered table-condensed table-hover">
		<tr>
			<th>课程名称</th>
			<th>课程状态</th>
			<th>操作</th>
		</tr>
  		{% for course in courses %}
    	<tr>
    		<td>{{ course.name }}</td>
    		<td>	{% if course.active == True %}
    					Active
    				{% else %}
    					Inactive
    				{% endif %}
    		</td>
    		<td><a href="/edit-course/{{course.id}}">编辑</a>
				<a href="/delete-course/{{course.id}}" onclick="return confirm('删除后不能还原，你确定吗?')">刪除</a>
			</td>
    	</tr>
    	{% endfor %}
	</table>
	
{% endblock %}

apps/templates/edit-course.html
{% extends "base.html" %}
{% block title %}
	Edit Course
{% endblock %}

{% block content %}
	<form action="{{ url_for('views.update_course', id=course.id) }}" method="post" id="post_new">
	<table class="table table-striped table-bordered table-condensed table-hover">
		<p><input type="hidden" value="{{ course.id }}"></input></p>
		<tr>
			<th>项目</th>
			<th></th>
		</tr>
		<tr>
			<td>课程名称</td>
			<td><input class="large" type="text" name="name" placeholder="{{ course.name }}" /></td>
		</tr>
		<tr>
			<td>科目</td>
			<td>
				{% for subject in course.subject %}
					<p><input type="checkbox" name="{{ subject.name }}" class="checkbox" /><label>{{ subject.name }}</label></p>
				{% endfor %}
			</td>
			
		</tr>
		<tr>
			<td>{% for student in course.students %}
					student.lastname ~ student.firstname
				{% endfor %}
			</td>
			
		</tr>

	</table>
	<p><input type="submit" class="submit" value="保存" /></p>
	</form>
{% endblock %}

apps/templates/edit-student.html
{% extends "base.html" %}

{% block title %}
	Edit Student
{% endblock %}

{% block content %}
	<form action="{{ url_for('views.update_student', id=student.id) }}" method="post" id="post_new">
		<table class="table table-striped table-bordered table-condensed table-hover">
			<tr>
				<th>项目</th>
				<th></th>
			</tr>
			<tr>
				<td>名字</td>
				<td><input type="text" name="name" class="long_txt" placeholder="{{ student.lastname ~ student.firstname }}"/></td>
			</tr>
			<tr>
				<td>生日</td>
				<td><input type="date" name="birthdate" class="long_txt" placeholder="{{ student.birthdate }}"/></td>
			</tr>
			<tr>
				<td>缴费情况</td>
				<td><input type="text" name="paid" class="long_txt" placeholder="{{ student.paid }}"/></td>
			</tr>
			<tr>
				<td>水平等级</td>
				<td><input type="text" name="level" class="long_txt" placeholder="{{ student.level }}"/></td>
			</tr>
			<tr>
				<td>课程</td>
				<td><input type="text" name="courses" class="long_txt" /></td>
			</tr>

		</table>
		<p><input type="submit" class="submit" value="保存" /></p>
	</form>
{% endblock %}

apps/templates/edit-subject.html
{% extends "base.html" %}

{% block title %}
	Edit Course
{% endblock %}

{% block content %}
	<form action="{{ url_for('views.update_subject', id=subject.id) }}" method="post" id="post_new">
	<table class="table table-striped table-bordered table-condensed table-hover">
		<p><input type="hidden" value="{{ subject.id }}"></input></p>
		<tr>
			<th>项目</th>
			<th></th>
		</tr>
		<tr>
			<td>科目名称</td>
			<td><input class="large" type="text" name="name" placeholder="{{ subject.name }}" /></td>
		</tr>
		<tr>
			<td>课时</td>
			<td>
				<p><input type="text" name="duration" class="checkbox" placeholder="{{ subject.duration }}"/></p>
			</td>
			
		</tr>
		<tr>
			
		</tr>

	</table>
	<p><input type="submit" class="submit" value="保存" /></p>
	</form>
{% endblock %}

apps/templates/home.html
{% extends "base.html" %}
{% set active_page = "home" %}
{% block title %}
	Courses system
{% endblock %}

{% block content %}
	{% if not g.user.is_authenticated()%}
		<span class="btn btn-default btn-lg"><a href="{{ url_for('auth.login') }}">Login</a></span></li>
		<span class="btn btn-default btn-lg"><a href="{{ url_for('auth.signup') }}">Signup now!</a></span>
	{% endif %}
	
	
{% endblock %}

apps/templates/login.html
{% extends "base.html" %}
{% block content %}
  <form action="" method=post class="form-horizontal">
    <h2>Welcome to Course System </h2>
    <div class="control-group">
        <div class="controls">
          <input type="text" id="username" name="username" class="input-xlarge"
            placeholder="Enter Username" required>
        </div>
    </div>
 
    <div class="control-group">
        <div class="controls">
          <input type="password" id="password" name="password" class="input-xlarge"
            placeholder="Enter Password" required>
        </div>
    </div>
 
    <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn btn-success">Signin</button>
        </div>
    </div>
  </form>
{% endblock %}

apps/templates/signup-success.html
{% extends "base.html" %}
{% block content %}

{% endblock %}

apps/templates/signup.html
{% extends "base.html" %}
{% block title %}{{page_title}}{% endblock %}
{% block content %}
<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-8 well" style="background-color: #ffffff">
    <!--<div class="container">-->
      <div class="row">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-8" >
          <form action="{{url_for('auth.signup')}}" class="form" method="POST">
            {{ form.hidden_tag() }}
            <div class="heading">
              <h4 class="form-heading">Welcome to Course System.</h4>
            </div>
            <div class="form-group {% if form.email.errors %} has-error {% endif %}">
              {{form.email.label()}}
              <div>
                {{ form.email(placeholder="E.g. brucewayne@wayne.com", class="form-control") }} 
              </div>
              <p class="help-block">
                {{ form.email.errors[0] }}

              </div>
              <div class="form-group {% if form.password.errors %} has-error {% endif %}">
                {{form.password.label()}}
                <div>
                  {{ form.password(placeholder="Min. 6 Characters", class="form-control") }}
                </div>
                <p class="help-block">
                  {{ form.password.errors[0] }}

              </div>
              <div class="form-group {% if form.confirm.errors %} has-error {% endif %}">
                {{form.confirm.label()}}
                <div>
                  {{ form.confirm(placeholder="Min. 6 Characters", class="form-control") }}
                </div>
                <p class="help-block">
                  {{ form.confirm.errors[0] }}

              </div>
              <div class="form-group {% if form.username.errors %} has-error {% endif %}">
                  {{form.username.label()}}
                  <div>
                    {{form.username(placeholder="E.g. vhd1001", class="form-control")}}
                  </div>
                  <p class="help-block">
                    {{ form.username.errors[0] }}

              </div>
              <div class="form-group {% if form.agree.errors %} has-error {% endif %}">
                    <label class="checkbox">
                      {{form.agree}} {{form.agree.label}}
                    </label>
                    <p class="help-block">
                      {{ form.agree.errors[0] }}

              </div>    
            <button class="btn btn-success" type="submit">Sign Up</button>
          </form>
        </div>
        <div class="col-sm-2">
        </div>
      </div>
    <!--</div>-->
  </div>
  <div class="col-sm-2">
  </div>
</div>
{% endblock %}

apps/templates/teachers.html
{% extends "base.html" %}
{% set active_page = "teachers" %}
{% block title %}
	Teacher page
{% endblock %}

{% block content %}
    
    <h2>新增老师</h2>
    <p></p>
	<form action="/new-teacher" method="post" id="post_new">
		<p><input class="large" type="text" name="firstname" placeholder="名字" /></p>
		<p><input class="large" type="text" name="lastname" placeholder="姓" /></p>
		<p><input class="large" type="date" name="birthdate" placeholder="生日" /></p>
		<p><input class="large" type="text" name="nationality" placeholder="国籍" /></p>
		<p><input class="large" type="text" name="visa_status" placeholder="签证情况" /></p>
		<p><input class="large" type="text" name="salary_per_hour" placeholder="时薪" /></p>
		<p><input type="submit" class="submit" value="添加" /></p>
	</form>

	</br>

	<h2>现有老师</h2>
	<table class="table table-striped table-bordered table-condensed table-hover">
		<tr>
			<th>名字</th>
			<th>生日</th>
			<th>签证情况</th>
			<th>国籍</th>
			<th>时薪</th>
			<th>操作</th>
		</tr>
  		{% for teacher in teachers %}
    	<tr>
    		<td>{{ teacher.lastname ~ teacher.firstname }}</td>
    		<td>{{ teacher.birthdate}}</td>	
    		<td>{{ teacher.visa_status}}</td>
    		<td>{{ teacher.nationality}}</td>
    		<td>{{ teacher.salary_per_hour}}</td>
    		<td><a href="{{ url_for('views.edit_teacher', id=teacher.id) }}">编辑</a>
				<a href="/delete-teacher/{{teacher.id}}" onclick="return confirm('删除后不能还原，你确定吗?')">刪除</a>
			</td>
    	</tr>
    	{% endfor %}
	</table>
	
{% endblock %}